### ISSUE TITLE
Finding ressources in KCL seems to be broken (but I am not sure)

### ISSUE THREAD

**Issue by barais** [dukeboard/kevoree-classloading-framework#5]
I just build a simple application. 

I clean the pom.xml for Kevoree with some excluse
https://github.com/barais/JHipsterKevoreeSample

The main start, and the same code in a start does not work. For me it seems that KCL has a bug with when spring boot and somme loggers tries to find some ressources. 

Olivier

**Comment by dukeboard** [comment]
Fix in KCL v23, big thank you for reporting the issue :-)
